services:
  - type: web
    name: n8n
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    plan: free
    envVars:
      - key: PORT
        value: 5678
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n.onrender.com
